<?php
$order = $block->getOrder();
$transaction = $block->getAmwalTransaction();
$isBankInstallmentsEnabled = $block->isBankInstallmentsEnabled();
$installmentUrl = $block->getInstallmentUrl();

function shouldDisplayInstallmentIframe($transaction, $isBankInstallmentsEnabled) {
    return $transaction && $isBankInstallmentsEnabled && $transaction->payment_method === 'Installments';
}
?>
<?php if (shouldDisplayInstallmentIframe($transaction, $isBankInstallmentsEnabled)): ?>
    <div class="order-success">
        <iframe
            src="<?php echo htmlspecialchars($installmentUrl, ENT_QUOTES, 'UTF-8'); ?>"
            width="100%"
            height="1000px"
            frameborder="0">
        </iframe>
    </div>
<?php endif; ?>
