<?php
$order = $block->getOrder();
$transaction = $block->getAmwalTransaction();
$installmentUrl = $block->getInstallmentUrl();

function shouldDisplayInstallmentIframe($transaction) {
    return $transaction && $transaction->payment_method === 'Installments';
}
?>
<?php if (shouldDisplayInstallmentIframe($transaction)): ?>
    <div class="order-success">
        <iframe
            src="<?php echo htmlspecialchars($installmentUrl, ENT_QUOTES, 'UTF-8'); ?>"
            width="100%"
            height="1000px"
            frameborder="0">
        </iframe>
    </div>
<?php endif; ?>
