<?php
$order = $block->getOrder();
$transaction = $block->getAmwalTransaction();
$isBankInstallmentsEnabled = $block->isBankInstallmentsEnabled();
$installmentUrl = $block->getInstallmentUrl();
?>

<?php if ($isBankInstallmentsEnabled && $transaction->payment_method == 'Installments'): ?>
    <div class="order-success">
        <iframe src="<?php echo $installmentUrl; ?>" width="100%" height="1000px" frameborder="0"></iframe>
    </div>
<?php endif; ?>
