name: "Bug Report"
description: Report a bug.
title: "[BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter a detailed description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Reproduction steps"
      description: Please provide a detailed explanation on how the bug can be reproduced
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected result"
      description: What would you expect to happen instead?
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output.
      render: bash
    validations:
      required: false
  - type: textarea
    id: browser
    attributes:
      label: "Browser"
      description: In which browser(s) did the issue occur? Please provide the name and version of the browser.
      placeholder: |
        * Chrome - Version 107.0.5304.87 (Official Build) (64-bit)
        * Firefox - 107.0 (64-bit)
      render: bash
    validations:
      required: false
  - type: textarea
    id: os
    attributes:
      label: "Operating System"
      description: In which operating system(s) did the issue occur?
      placeholder: |
        * Ubuntu 20.04.4 LTS (64-bit)
        * Windows 10 (64-bit)
      render: bash
    validations:
      required: false
