<?php
/**
 * Merchant ID Verification Button Template
 *
 * @var \Amwal\Payments\Block\System\Config\ValidateMerchantIdButton $block
 */
?>
<!-- Merchant Verification Button -->
<button
    class="scalable"
    type="button"
    id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"
    data-mage-init='<?= /* @noEscape */ json_encode([
        'verifyMerchantId' => [
            'baseUrl' => $block->getApiUrl(),
            'elementId' => $block->getHtmlId(),
            'successText' => __('Merchant ID is valid!'),
            'failedText' => __('Invalid Merchant ID provided!')
        ]
    ]) ?>'>
    <span id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>_result">
        <?= $block->escapeHtml($block->getButtonLabel()) ?>
    </span>
</button>
