<?php
/** @var \Amwal\Payments\Block\ExpressCheckoutMinicartButton $block */
/** @var \Amwal\Payments\ViewModel\ExpressCheckoutButton $viewModel */
$viewModel = $block->getViewModel();
$quote = $block->getQuote();
$quoteId = $quote ? $quote->getId() : 'newquote';
$viewModel->setQuoteId((string)$quoteId);
?>
<div id="amwal-minicart-button" class="amwal-express-checkout-button hidden">
    <amwal-checkout-button
        merchant-id="<?= $viewModel->getMerchantId() ?>"
        amount="<?= $quote ? $quote->getSubtotal() : 0 ?>"
        country-code="<?= $viewModel->getCountryCode() ?>"
        locale="<?= $viewModel->getLocale() ?>"
        dark-mode="<?= $viewModel->isDarkModeEnabled() ? 'on' : 'off' ?>"
        email-required="<?= $viewModel->isCustomerLoggedIn() ? 'false' : 'true' ?>"
        address-required="true"
        address-handshake="true"
        shipping-methods='[{"id":"to-be-determined1","label":"To be determined 1","price":0},{"id":"to-be-determined2","label":"To be determined 2","price":0}]'
        ref-id="<?= $viewModel->getRefId() ?>"
        label="quick-buy"
        id="amwal-checkout-quote-<?= $quoteId ?>"
        <?php if ($viewModel->getMerchantMode() === \Amwal\Payments\Model\Config\Source\MerchantMode::MERCHANT_TEST_MODE): ?>
            test-environment="qa"
        <?php endif; ?>/>
<script type="text/x-magento-init">
    {
        "#amwal-checkout-quote-<?= $quoteId ?>": {
            "Amwal_Payments/js/checkout-button-minicart": {
                "hideProceedToCheckout": <?= (int) $viewModel->shouldHideProceedToCheckout() ?>,
                "quotePrice": "<?= $quote ? $quote->getSubtotal() : 0 ?>",
                "quoteId": "<?= $quoteId ?>",
                "refId": "<?= $viewModel->getRefId() ?>",
                "refIdData": <?= $viewModel->getRefIdData()->toJson() ?>,
                "customerId": "<?= $viewModel->getCustomerId() ?>"
            }
        }
    }
</script>
