<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Amwal\Payments\Block\ExpressCheckoutMinicartButton $block */
/** @var \Amwal\Payments\ViewModel\ExpressCheckoutButton $viewModel */
$viewModel = $block->getViewModel();
$quote = $block->getQuote();
$quoteId = $quote ? $quote->getId() : 'newquote';
$viewModel->setQuoteId((string)$quoteId);
?>
<div id="amwal-cart-button" class="amwal-express-checkout-button" trigger-context="cart">
</div>
<script>
    window.addEventListener("DOMContentLoaded", (event) => {
        if (window.renderReactElement){
            const cartButtonContainer = document.getElementById('amwal-cart-button');
            window.renderReactElement(cartButtonContainer);
        }
    })
</script>
