<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Amwal\Payments\ViewModel\ExpressCheckoutButton $viewModel */
$viewModel = $this->getViewModel();
$product =$viewModel->getProduct();
$productPrice = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
$configurableOptions = $viewModel->getConfigurableOptions($product);
?>

<?php if ($viewModel->isExpressCheckoutActive()): ?>
    <div class="amwal-express-checkout-button" trigger-context="product-listing-page" id="amwal-product-button-<?= $product->getId() ?>">
    </div>
    <script>
        window.addEventListener("DOMContentLoaded", (event) => {
            if (window.renderReactElement){
                const cartButtonContainer = document.getElementById("amwal-product-button-<?= $product->getId() ?>");
                window.renderReactElement(cartButtonContainer);
            }
        })
    </script>
<?php endif; ?>
