<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Catalog\Block\Product\AbstractProduct $block */
/** @var \Amwal\Payments\ViewModel\ExpressCheckoutButton $viewModel */
$viewModel = $this->getViewModel();
$product = $block->getProduct();
$viewModel->setProduct($product);
$productPrice = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
?>
<?php if ($viewModel->isExpressCheckoutActive() && !$viewModel->isProductConfigurable($product)): ?>
    <div class="amwal-express-checkout-button" trigger-context="product-listing-page" id="amwal-product-button-<?= $product->getId() ?>">
    </div>
    <script>
        window.addEventListener("DOMContentLoaded", (event) => {
            if (window.renderReactElement){
                const cartButtonContainer = document.getElementById("amwal-product-button-<?= $product->getId() ?>");
                window.renderReactElement(cartButtonContainer);
            }
        })
    </script>
<?php endif; ?>
