<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Amwal\Payments\ViewModel\ExpressCheckoutButton $viewModel */
$viewModel = $this->getViewModel();
$product =$viewModel->getProduct();
$productPrice = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
$configurableOptions = $viewModel->getConfigurableOptions($product);
?>

<?php if ($viewModel->isExpressCheckoutActive()): ?>
    <div class="amwal-express-checkout-button">
        <amwal-checkout-button
            merchant-id="<?= $viewModel->getMerchantId() ?>"
            amount="<?= $productPrice ?>"
            country-code="<?= $viewModel->getCountryCode() ?>"
            locale="<?= $viewModel->getLocale() ?>"
            dark-mode="<?= $viewModel->isDarkModeEnabled() ? 'on' : 'off' ?>"
            email-required="<?= $viewModel->isCustomerLoggedIn() ? 'false' : 'true' ?>"
            address-required="true"
            address-handshake="true"
            shipping-methods='[]'
            ref-id="<?= $viewModel->getRefId() ?>"
            label="quick-buy"
            disabled="true"
            allowed-address-countries='<?= $viewModel->getAllowedCountriesJson() ?>'
            id="amwal-checkout-<?= $product->getId() ?>"
            <?php foreach ($viewModel->getInitialDataAttributes() as $attribute => $value): ?>
                <?= $attribute ?>='<?= $escaper->escapeHtmlAttr($value) ?>'
            <?php endforeach; ?>
            <?php if ($viewModel->getMerchantMode() === \Amwal\Payments\Model\Config\Source\MerchantMode::MERCHANT_TEST_MODE): ?>
                test-environment="qa"
            <?php endif; ?>/>
    </div>
    <script type="text/x-magento-init">
        {
            "#amwal-checkout-<?= $product->getId() ?>": {
                "Amwal_Payments/js/checkout-button-product": {
                    "productId": "<?= $product->getId() ?>",
                    "refId": "<?= $viewModel->getRefId() ?>",
                    "refIdData": <?= $viewModel->getRefIdData()->toJson() ?>,
                    "configuredProductId": "<?= $product->getId() ?>",
                    "configuration": {},
                    "productPrice": "<?= $productPrice ?>",
                    "isConfigurable": <?= $viewModel->isProductConfigurable($product) ? 'true' : 'false' ?>,
                    "configurableOptions": <?= $viewModel->getConfigurableOptions($product) ? json_encode($viewModel->getConfigurableOptions($product)) : '"{}"' ?>
                }
            }
        }
    </script>
<?php endif; ?>
