<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Amwal\Payments\Block\ExpressCheckoutMinicartButton $block */
/** @var \Amwal\Payments\ViewModel\ExpressCheckoutButton $viewModel */
$viewModel = $block->getViewModel();
$quote = $block->getQuote();
$quoteId = $quote ? $quote->getId() : 'newquote';
$viewModel->setQuoteId((string)$quoteId);
$bundleUrl = $block->getViewFileUrl('Amwal_Payments/js/react-src/dist/bundle.js') 
?>
<div id="amwal-cart-button" class="amwal-express-checkout-button">
</div>
<script type="text/javascript" src="<?= $bundleUrl ?>"></script>

