<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Amwal\Payments\Block\ExpressCheckoutMinicartButton $block */
/** @var \Amwal\Payments\ViewModel\ExpressCheckoutButton $viewModel */
$viewModel = $block->getViewModel();
$quote = $block->getQuote();
$quoteId = $quote ? $quote->getId() : 'newquote';
$viewModel->setQuoteId((string)$quoteId);
?>
<div id="amwal-minicart-button" class="amwal-express-checkout-button hidden">
    <amwal-checkout-button
        merchant-id="<?= $escaper->escapeHtmlAttr($viewModel->getMerchantId()) ?>"
        amount="<?= $escaper->escapeHtmlAttr($quote ? $quote->getSubtotal() : 0) ?>"
        country-code="<?= $escaper->escapeHtmlAttr($viewModel->getCountryCode()) ?>"
        locale="<?= $escaper->escapeHtmlAttr($viewModel->getLocale()) ?>"
        dark-mode="<?= $escaper->escapeHtmlAttr($viewModel->isDarkModeEnabled() ? 'on' : 'off') ?>"
        email-required="<?= $escaper->escapeHtmlAttr($viewModel->isCustomerLoggedIn() ? 'false' : 'true') ?>"
        address-required="true"
        address-handshake="true"
        shipping-methods='[]'
        ref-id="<?= $escaper->escapeHtmlAttr($viewModel->getRefId()) ?>"
        label="quick-buy"
        allowed-address-countries='<?= $escaper->escapeHtmlAttr($viewModel->getAllowedCountriesJson()) ?>'
        enable-pre-pay-trigger="true"
        id="amwal-checkout-minicart-<?= $escaper->escapeHtmlAttr($quoteId) ?>"
        <?php if ($limitRegions = $viewModel->getLimitedRegionCodesJson()): ?>
            allowed-address-states='<?= $escaper->escapeHtmlAttr($limitRegions) ?>'
        <?php endif; ?>
        <?php foreach ($viewModel->getInitialDataAttributes() as $attribute => $value): ?>
            <?= $attribute ?>='<?= $escaper->escapeHtmlAttr($value) ?>'
        <?php endforeach; ?>
        <?php if ($viewModel->getMerchantMode() === \Amwal\Payments\Model\Config\Source\MerchantMode::MERCHANT_TEST_MODE): ?>
            test-environment="qa"
        <?php endif; ?>/>
<script type="text/x-magento-init">
    {
        "#amwal-checkout-minicart-<?= $quoteId ?>": {
            "Amwal_Payments/js/checkout-button-minicart": {
                "hideProceedToCheckout": <?= (int) $viewModel->shouldHideProceedToCheckout() ?>,
                "quotePrice": "<?= $quote ? $quote->getSubtotal() : 0 ?>",
                "quoteId": "<?= $quoteId ?>",
                "refId": "<?= $viewModel->getRefId() ?>",
                "refIdData": <?= $viewModel->getRefIdData()->toJson() ?>,
                "customerId": "<?= $viewModel->getCustomerId() ?>"
            }
        }
    }
</script>
