<?php
use Magento\Catalog\Block\Product\ProductList\Item\Block;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Amwal\Payments\ViewModel\ExpressCheckoutButton;

/**
 * @var Escaper $escaper
 * @var Template|Block $block
 * @var ExpressCheckoutButton $viewModel
 */
$viewModel = $this->getViewModel();
$buttonId = $viewModel->getUniqueId();
$triggerContext = $block->getTriggerContext();
$formSelector = $viewModel->getFormSelector($this->getFormSelector(), $block->getProduct());
$checkoutButtonId = $viewModel->getCheckoutButtonId();
?>
<?php if ($viewModel->shouldRender($triggerContext)): ?>
    <?php if ($triggerContext === ExpressCheckoutButton::TRIGGER_CONTEXT_LOGIN): ?>
        <div class="block block-customer-login amwal-express-checkout-or hidden" style="margin-bottom: 25px;">
            <svg height="5" width="215">
                <line x1="0" y1="0" x2="210" y2="0" style="stroke:#969393;stroke-width:3" >
            </svg> OR
            <svg height="5" width="210">
                <line x1="0" y1="0" x2="210" y2="0" style="stroke:#969393;stroke-width:3" >
            </svg>
        </div>
    <?php endif; ?>
    <div class="amwal-express-checkout-button <?= $escaper->escapeHtmlAttr($triggerContext) ?><?= in_array($triggerContext, [ExpressCheckoutButton::TRIGGER_CONTEXT_MINICART, ExpressCheckoutButton::TRIGGER_CONTEXT_LOGIN]) ? ' hidden' : '' ?>"
         data-trigger-context="<?= $escaper->escapeHtmlAttr($triggerContext) ?>"
         data-locale="<?= $escaper->escapeHtmlAttr($viewModel->getLocale()) ?>"
         data-scope-code="<?= $escaper->escapeHtmlAttr($viewModel->getStoreCode()) ?>"
         data-product-id="<?= $triggerContext === ExpressCheckoutButton::TRIGGER_CONTEXT_MINICART ? '' : $escaper->escapeHtmlAttr($viewModel->getProductId()) ?>"
         data-button-id="<?= $escaper->escapeHtmlAttr($checkoutButtonId) ?>"
         <?= $formSelector ? 'data-form-selector="' . $escaper->escapeHtmlAttr($formSelector) . '"' : '' ?>
         id="<?= $escaper->escapeHtmlAttr($buttonId) ?>"
    >
    </div>
    <script type="text/x-magento-init">
        {
            "#<?= $buttonId ?>": {
                "Amwal_Payments/js/checkout-button": {
                    "buttonId" : "<?= $buttonId ?>",
                    "triggerContext": "<?= $triggerContext ?>",
                    "hideProceedToCheckout": <?= $viewModel->shouldHideProceedToCheckout()? "true": "false" ?>
                }
            }
        }
    </script>
<?php endif; ?>
<style>
    <?= $viewModel->getStyleCss() ?>
</style>
