<?php
use Magento\Catalog\Block\Product\ProductList\Item\Block;
use Magento\Framework\View\Element\Template;
use Amwal\Payments\ViewModel\ExpressCheckoutButton;

/**
 * @var Template|Block $block
 * @var ExpressCheckoutButton $viewModel
 */
$viewModel = $this->getViewModel();
$buttonId = $viewModel->getUniqueId();
$triggerContext = $block->getTriggerContext();
$formSelector = $viewModel->getFormSelector($this->getFormSelector(), $block->getProduct());
?>
<style>
    <?= $viewModel->getStyleCss() ?>
</style>
<?php if ($viewModel->shouldRender($triggerContext)): ?>
    <div class="amwal-express-checkout-button<?= $triggerContext === ExpressCheckoutButton::TRIGGER_CONTEXT_MINICART ? ' hidden' : '' ?> <?= $triggerContext ?>"
         data-trigger-context="<?= $triggerContext ?>"
         data-locale="<?= $viewModel->getLocale() ?>"
         data-scope-code="<?= $viewModel->getStoreCode() ?>"
        <?= $formSelector ? 'data-form-selector="' . $formSelector . '"' : '' ?>
         id="<?= $buttonId ?>"
    >
    </div>
    <script type="text/x-magento-init">
        {
            "#<?= $buttonId ?>": {
                "Amwal_Payments/js/checkout-button": {
                    "buttonId" : "<?= $buttonId ?>",
                    "triggerContext": "<?= $triggerContext ?>",
                    "hideProceedToCheckout": <?= $viewModel->shouldHideProceedToCheckout()? "true": "false" ?>
        }
    }
}
    </script>
<?php endif; ?>