<div class="amwal-installments-timeline"
     data-enable-installments="false"
     data-locale="en"
     data-amount="22"
     data-installments-count="6"
     data-border="true"
     id="amwal-installments-timeline">
</div>

<script type="text/x-magento-init">
    {
        "#amwal-installments-timeline": {
            "Amwal_Payments/js/installments-timeline": {
                "timelineId": "amwal-installments-timeline"
            }
        }
    }
</script>
