#
# Todo: Revisit/Rewrite unit tests before adding them to actions
#
#name: Unit Tests
#on: push
#jobs:
#  mage246:
#    name: Magento 2.4.6 Unit Tests
#    runs-on: ubuntu-latest
#    env:
#      MODULE_NAME: ${{ secrets.MODULE_NAME }}
#      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
#    steps:
#      - uses: actions/checkout@v4
#      - uses: extdn/github-actions-m2/magento-unit-tests/8.2@master
#        env:
#          MAGENTO_VERSION: '2.4.6'
#
#  mage245:
#    name: Magento 2.4.5 Unit Tests
#    runs-on: ubuntu-latest
#    env:
#      MODULE_NAME: ${{ secrets.MODULE_NAME }}
#      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
#    steps:
#      - uses: actions/checkout@v4
#      - uses: extdn/github-actions-m2/magento-unit-tests/8.1@master
#        env:
#          MAGENTO_VERSION: '2.4.5'
#
#  mage244:
#    name: Magento 2.4.4 Unit Tests
#    runs-on: ubuntu-latest
#    env:
#      MODULE_NAME: ${{ secrets.MODULE_NAME }}
#      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
#    steps:
#      - uses: actions/checkout@v4
#      - uses: extdn/github-actions-m2/magento-unit-tests/7.4@master
#        env:
#          MAGENTO_VERSION: '2.4.4'
