<?php
/** @var int $orderId */
$orderId = $this->getData('orderId');
?>
<button class="action-default scalable primary amwal-refund-button" type="button" data-order-id="<?= $orderId ?>">
    <?= __('Refund with Amwal') ?>
</button>

<script>
    require(['jquery', 'mage/translate'], function ($, $t) {
        $(document).ready(function () {
            $('.amwal-refund-button').click(function () {

                let orderId = $(this).data('orderId');
                let refundReason = $('textarea[name="creditmemo[comment_text]"]').val();
                let refundAmount = 0;
                let shippingAmount = $('input[name="creditmemo[shipping_amount]"]').val();
                let adjustmentPositive = $('input[name="creditmemo[adjustment_positive]"]').val();
                let adjustmentNegative = $('input[name="creditmemo[adjustment_negative]"]').val();

                let totalDiscount = 0;
                $('table.order-creditmemo-tables td.col-discont span.price').each(function () {
                    totalDiscount = $(this).text().replace(/[^0-9.-]+/g, "");
                });

                let totalTax = 0;
                $('table.order-creditmemo-tables td.col-tax-amount span.price').each(function () {
                    totalTax = $(this).text().replace(/[^0-9.-]+/g, "");
                });

                $('table.order-subtotal-table tfoot span.price').each(function () {
                    refundAmount = $(this).text().replace(/[^0-9.-]+/g, "");
                });
                if (shippingAmount > 0) {
                    alert($t('The shipping amount will not be returned until the last time the refund is made.'));
                }
                if (!confirm($t('Are you sure you want to refund ' + refundAmount + ' with Amwal Payments?'))) {
                    return;
                }
                let refundItems = [];
                $('input[name^="creditmemo[items]"]').each(function () {
                    if ($(this).attr('name').indexOf('qty') === -1 || $(this).val() === '0') {
                        return;
                    }
                    let itemId = $(this).attr('name').replace('creditmemo[items][', '').replace(']', '');
                    itemId = itemId.replace(/\[[^\]]*\]/g, '');

                    let itemQty = $(this).val();
                    let itemTax = $(this).parent().next().next().text().replace(/[^0-9.-]+/g, "");
                    let discountAmount = $(this).parent().next().next().next().text().replace(/[^0-9.-]+/g, "");
                    let itemPrice = $(this).parent().next().next().next().next().text().replace(/[^0-9.-]+/g, "");

                    refundItems.push({
                        item_id: itemId,
                        qty: itemQty,
                        tax: itemTax,
                        discount_amount: discountAmount,
                        price: itemPrice
                    });
                });

                fetch('/rest/V1/amwal/refand', {
                    method: 'POST',
                    body: JSON.stringify({
                        order_id: orderId,
                        refund_amount: refundAmount,
                        shipping_amount: shippingAmount,
                        adjustment_positive: adjustmentPositive,
                        adjustment_negative: adjustmentNegative,
                        total_discount: totalDiscount,
                        total_tax: totalTax,
                        refund_items: refundItems,
                        refund_reason: refundReason
                    }),
                    headers: {
                        'Content-Type': 'application/json'
                    }
                })
                .then((response) => response.json())
                .then(function (response) {
                    response = response[0] || response;
                    if (response.status) {
                        window.history.back();
                    } else {
                        alert(response.message);
                    }
                }).catch(function (response) {
                    console.log(response);
                });
            });
        });
    });
</script>
