name: Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Extract Branch Name
        id: extract_branch
        run: |
          BRANCH_NAME=$(echo "$GITHUB_REF" | sed 's/refs\/heads\///')
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Get The Branch Name
        run: echo "The branch name is ${{ env.BRANCH_NAME }}"

      - name: Install Dependencies
        run: echo "composer packgae amwal/payments:dev-${{ env.BRANCH_NAME }}"

      - name: Reset Amwal Github folder
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER }} "cd /var/www/html/vendor/amwal/payments && git reset --hard"

      - name: Install Dependencies and Upgrade
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER }} "cd /var/www/html && composer require amwal/payments:dev-${{ env.BRANCH_NAME }} && bin/magento setup:upgrade && bin/magento setup:di:compile && bin/magento setup:static-content:deploy -f && bin/magento cache:flush"

      - name: Set the permission
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER }} "chmod -R 777 /var/www/html"
