name: Integration Tests
on: [push,pull_request]

jobs:
  integration-tests:
    name: Magento 2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.16
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      MODULE_NAME: ${{ secrets.MODULE_NAME }}
      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
      ELASTICSEARCH: 1
      MAGENTO_POST_INSTALL_SCRIPT: 'config/post-install-config.sh'
    steps:
      - uses: actions/checkout@v4
#      - uses: extdn/github-actions-m2/magento-integration-tests/7.4@master
#        env:
#          MAGENTO_VERSION: '2.4.3-p3'
#          COMPOSER_VERSION: '2'
      - uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        env:
          MAGENTO_VERSION: '2.4.4-p7'
          COMPOSER_VERSION: '2'
#      - uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
#        env:
#          MAGENTO_VERSION: '2.4.6-p4'
#          COMPOSER_VERSION: '2'