name: Integration Tests
on: [push,pull_request]

jobs:
  integration-tests:
    name: Magento 2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      rabbitmq:
        image: rabbitmq:3.9-alpine
        env:
          RABBITMQ_DEFAULT_USER: "magento"
          RABBITMQ_DEFAULT_PASS: "magento"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - 5672:5672
      es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        ports:
          - 9200:9200
          - 9300:9300
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    env:
      MODULE_NAME: ${{ secrets.MODULE_NAME }}
      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
      ELASTICSEARCH: 1
    steps:
      - uses: actions/checkout@v4
#      - uses: extdn/github-actions-m2/magento-integration-tests/7.4@master
#        env:
#          MAGENTO_VERSION: '2.4.3-p3'
#          COMPOSER_VERSION: '2'
      - uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        env:
          MAGENTO_VERSION: '2.4.4-p7'
          COMPOSER_VERSION: '2'
#      - uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
#        env:
#          MAGENTO_VERSION: '2.4.6-p4'
#          COMPOSER_VERSION: '2'