name: Static code analysis

on:
  pull_request:
  push:

jobs:
  analyse:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5 -e MYSQL_ROOT_PASSWORD=magento -e MYSQL_USER=magento -e MYSQL_PASSWORD=magento -e MYSQL_DATABASE=magento --entrypoint sh mysql:8.0 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
      rabbitmq:
        image: docker://rabbitmq:3.9-alpine
        env:
          RABBITMQ_DEFAULT_USER: "magento"
          RABBITMQ_DEFAULT_PASS: "magento"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - 5672:5672
      opensearch:
        image: ghcr.io/mad-i-t/magento-opensearch:2.5.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" -e "plugins.security.disabled=true" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: Amwal_Payments

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: none, bcmath, curl, dom, fileinfo, gd, iconv, intl, mbstring, pdo_mysql, simplexml, soap, sockets, tokenizer, xsl, zip, simplexml, xml, xmlwriter, xmlreader
          coverage: none

      - name: Install Fresh Magento Repo
        if: ${{true}}
        uses: MAD-I-T/magento-actions@master
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'create-project'
          magento_version: 2.4.6
          no_push: 1

      - name: Configure GitHub Token
        run: composer config --global --auth github-oauth.github.com ${{ secrets.GIT_TOKEN }}

      - run: composer validate --strict

      - working-directory: .dev-tools
        run: composer install

      - working-directory: .dev-tools
        run: composer normalize --diff --dry-run --indent-size=4 --indent-style=space ../composer.json

      - working-directory: .dev-tools
        run: ./vendor/bin/php-cs-fixer fix -vvv --diff --dry-run

      - working-directory: .dev-tools
        run: ls -la

      - working-directory: .dev-tools
        run: ./vendor/bin/phpstan

      - working-directory: .dev-tools
        run: ./vendor/bin/psalm --no-progress --shepherd
