name: Tests

on:
  pull_request:

jobs:
  analyse:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: none, bcmath, curl, dom, fileinfo, gd, iconv, intl, mbstring, pdo_mysql, simplexml, soap, sockets, tokenizer, xsl, zip, simplexml, xml, xmlwriter, xmlreader
          coverage: none

      - name: Configure GitHub Token
        run: composer config --global --auth github-oauth.github.com ${{ secrets.GIT_TOKEN }}

      - run: composer validate --strict

      - name: Install Dependencies
        working-directory: .dev-tools
        run: composer install

      - name: Execute tests
        working-directory: .dev-tools
        run: ./vendor/bin/phpunit --configuration=../phpunit.xml --coverage-clover=../build/logs/clover.xml --log-junit=../build/logs/junit.xml
